spring:
  profiles:
    active: local

server:
  port: 8990

logging.level.org.springframework.batch: DEBUG
spring.batch.job.names: ${job.name:NONE}

---
spring.profiles: local
spring.profiles.include: local-social

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/shoppingmall?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

chunkSize: 100
pageSize: 100
poolSize: 10

---
spring.profiles: real
spring.profiles.include: real-product-purchase-count-batch
